### ISSUE TITLE
Simplification idea

### ISSUE THREAD

**Issue by crazy4groovy** [TehShrike/idle-until-urgent#3]
Well done, great idea for a function! I've simplified it a bit, take a look if interested:

https://gist.github.com/crazy4groovy/0320e065af1cc1d070679293521d6320

Cheers! 🍻

**Comment by TehShrike** [comment]
Cool!  My brain finds it a bit simpler to have the idle polyfill abstracted into its own file, but I can see why some might prefer having them in the same file.

One thing to note - you probably don't want to use `requestAnimationFrame` if it's available, since it will probably call your function at the point where the browser is *least* idle.

**Comment by crazy4groovy** [comment]
Good point - I've heard of the "double RAF" rule to help with that performance issue.
https://medium.com/@owencm/one-weird-trick-to-performant-touch-response-animations-with-react-9fe4a0838116

**Comment by TehShrike** [comment]
Nah, that's not quite what I meant - I mean, no matter when your rAF callback is called, it is by definition being called at a point where you don't want to do heavy work, because it is blocking an animation frame.

But probably more relevantly, there's probably still a ton of render/js work happening one or two animation frames after the initial run.  That's why I defaulted the timeout to 1000ms, because there could be a lot of churn going on during the first few hundred milliseconds depending on your html/css.

This post is related: https://nolanlawson.com/2018/09/25/accurately-measuring-layout-on-the-web/

**Comment by crazy4groovy** [comment]
Another good point -- so I added a `affectsDOM` param, to help reduce the chance of jank.
